version : '3'
 
services:
  reportsapi:
    image: reportsapi
    ports:
      - 9010:8080
    environment:
      - peopleapi_baseurl=http://peopleapi:8080/api/people/
      - clientapi_baseurl=http://clientapi:8080/api/clients/
      - salesapi_baseurl=http://salesapi:8080/salesapi/api/sales/
      - inventoryapi_baseurl=http://inventoryapi:8080/api/inventory/
    depends_on:
      - clientapi
      - inventoryapi
      - salesapi
      - peopleapi

  clientapi:
    image: clientapi
    ports:
      - 9000:8080
    depends_on:
      - clientapidb
  
  clientapidb:
    image: clientapidb
    ports:
      - 3306

  inventoryapi:
    image: inventoryapi
    ports:
      - 9002:8080
    depends_on:
      - inventoryapidb
  
  inventoryapidb:
    image: inventoryapidb
    ports:
      - 5432

  salesapi:
    image: salesapi
    ports:
      - 9006:8080
    depends_on:
      - salesapidb
  
  salesapidb:
    image: salesapidb
    ports:
      - 27017

  peopleapi:
    image: peopleapi
    ports:
      - 9004:8080
    environment:
      - peopleapi-context=server=peopleapidb;user id=peopleAPI;password=myP@ssw0rd;Database=peopleAPI
    depends_on:
      - peopleapidb
  
  peopleapidb:
    image: peopleapidb
    ports:
      - 1433
